
-- Users table
create table users (
    authorid   bigint generated by default as identity primary key,
    authorname varchar(255) not null unique,
    gender     varchar(10)         check (gender in ('Male', 'Female')),
    age        integer         check (age > 0),
    followers  integer default 0         check (followers >= 0),
    following  integer default 0         check (following >= 0),
    password   varchar(255),
    isdeleted  boolean default false
);

-- Recipes table
create table recipes (
    recipeid            bigint generated by default as identity primary key,
    name                varchar(500) not null,
    authorid            bigint       not null         references users(authorid),
    cooktime            varchar(50),
    preptime            varchar(50),
    totaltime           varchar(50),
    datepublished       timestamp,
    description         text,
    recipecategory      varchar(255),
    aggregatedrating    numeric(3, 2)         check (aggregatedrating >= 0 AND aggregatedrating <= 5),
    reviewcount         integer default 0         check (reviewcount >= 0),
    calories            numeric(10, 2),
    fatcontent          numeric(10, 2),
    saturatedfatcontent numeric(10, 2),
    cholesterolcontent  numeric(10, 2),
    sodiumcontent       numeric(10, 2),
    carbohydratecontent numeric(10, 2),
    fibercontent        numeric(10, 2),
    sugarcontent        numeric(10, 2),
    proteincontent      numeric(10, 2),
    recipeservings      varchar(100),
    recipeyield         varchar(100)
);

-- Reviews table
-- IMPORTANT: Added GENERATED BY DEFAULT AS IDENTITY for auto-increment support
create table reviews (
    reviewid      bigint generated by default as identity primary key,
    recipeid      bigint not null         references recipes(recipeid),
    authorid      bigint not null         references users(authorid),
    rating        integer,
    review        text,
    datesubmitted timestamp,
    datemodified  timestamp
);

-- Recipe Ingredients table
create table recipe_ingredients (
    recipeid       bigint       not null         references recipes(recipeid),
    ingredientpart varchar(500) not null,
    primary key (recipeid, ingredientpart)
);

-- Review Likes table
create table review_likes (
    reviewid bigint not null         references reviews(reviewid),
    authorid bigint not null         references users(authorid),
    primary key (reviewid, authorid)
);

-- User Follows table
create table user_follows (
    followerid  bigint not null         references users(authorid),
    followingid bigint not null         references users(authorid),
    primary key (followerid, followingid),
    check (followerid <> followingid)
);

-- Indexes for performance optimization
CREATE INDEX idx_recipes_author ON recipes(authorid);
CREATE INDEX idx_reviews_recipe ON reviews(recipeid);
CREATE INDEX idx_reviews_author ON reviews(authorid);
CREATE INDEX idx_user_follows_following ON user_follows(followingid);

-- Additional indexes for search and sort optimization
CREATE INDEX idx_recipes_category ON recipes(recipecategory);
CREATE INDEX idx_recipes_rating ON recipes(aggregatedrating);
CREATE INDEX idx_recipes_date ON recipes(datepublished);
CREATE INDEX idx_recipes_calories ON recipes(calories);
